## 3. Preprocessing

### a. Load Dataset

In [2]:
import pandas as pd

dataset = pd.read_csv('../data/processed/harga_gabungan.csv')
dataset.head()

      tanggal wilayah                   komoditas    harga
0  2019-01-01    Aceh  Bawang Merah Ukuran Sedang      NaN
1  2019-02-01    Aceh  Bawang Merah Ukuran Sedang  29750.0
2  2019-03-01    Aceh  Bawang Merah Ukuran Sedang  29000.0
3  2019-04-01    Aceh  Bawang Merah Ukuran Sedang  37100.0
4  2019-05-01    Aceh  Bawang Merah Ukuran Sedang  37100.0

### b. Sort Data

In [3]:
dataset['tanggal'] = pd.to_datetime(dataset['tanggal'])
dataset = dataset.sort_values(['wilayah', 'komoditas', 'tanggal']).reset_index(drop=True)

dataset.head()

     tanggal wilayah                   komoditas    harga
0 2019-01-01    Aceh  Bawang Merah Ukuran Sedang      NaN
1 2019-02-01    Aceh  Bawang Merah Ukuran Sedang  29750.0
2 2019-03-01    Aceh  Bawang Merah Ukuran Sedang  29000.0
3 2019-04-01    Aceh  Bawang Merah Ukuran Sedang  37100.0
4 2019-05-01    Aceh  Bawang Merah Ukuran Sedang  37100.0

### c. Handle Missing Value (ffill)

In [4]:
dataset['harga'] = dataset.groupby(['wilayah', 'komoditas'])['harga'].transform('ffill')

dataset = dataset.dropna(subset=['harga'])
print("Shape setelah ffill & drop awal:", dataset.shape)

Shape setelah ffill & drop awal: (17905, 4)

### d. Lags and Time

In [ ]:
import numpy as np

dataset['tahun'] = dataset['tanggal'].dt.year
dataset['bulan'] = dataset['tanggal'].dt.month
dataset['kuartal'] = dataset['tanggal'].dt.quarter

dataset['harga_lag1'] = dataset.groupby(['wilayah', 'komoditas'])['harga'].shift(1)
dataset['harga_lag2'] = dataset.groupby(['wilayah', 'komoditas'])['harga'].shift(2)
dataset['harga_lag3'] = dataset.groupby(['wilayah', 'komoditas'])['harga'].shift(3)
dataset['harga_lag12'] = dataset.groupby(['wilayah', 'komoditas'])['harga'].shift(12)

dataset['harga_rolling3'] = dataset.groupby(['wilayah', 'komoditas'])['harga'].transform(lambda x: x.shift(1).rolling(3).mean())
dataset['harga_rolling12'] = dataset.groupby(['wilayah', 'komoditas'])['harga'].transform(lambda x: x.shift(1).rolling(12).mean())

dataset['sin_bulan'] = np.sin(2 * np.pi * dataset['bulan'] / 12)
dataset['cos_bulan'] = np.cos(2 * np.pi * dataset['bulan'] / 12)

lebaran_months = {2019: 6, 2020: 5, 2021: 5, 2022: 5, 2023: 4, 2024: 4, 2025: 3, 2026: 3, 2027: 2, 2028: 2}
dataset['is_lebaran_month'] = dataset.apply(lambda row: 1 if lebaran_months.get(row['tahun']) == row['bulan'] else 0, axis=1)

dataset['tren_index'] = dataset.groupby(['wilayah', 'komoditas']).cumcount() + 1

dataset = dataset.dropna().reset_index(drop=True)

print("Shape setelah Feature Engineering:", dataset.shape)

Shape setelah Feature Engineering: (17281, 11)

### e. Split Dataset

In [6]:
CUTOFF_DATE = '2024-11-01'

train_df = dataset[dataset['tanggal'] < CUTOFF_DATE].copy()
test_df  = dataset[dataset['tanggal'] >= CUTOFF_DATE].copy()

print("Periode Training :", train_df['tanggal'].min().date(), "→", train_df['tanggal'].max().date())
print("Periode Testing  :", test_df['tanggal'].min().date(), "→", test_df['tanggal'].max().date())
print("Shape Train:", train_df.shape)
print("Shape Test :", test_df.shape)

Periode Training : 2019-04-01 → 2024-10-01
Periode Testing  : 2024-11-01 → 2026-04-01
Shape Train: (13572, 11)
Shape Test : (3709, 11)

### f. Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_wilayah = LabelEncoder()
le_komoditas = LabelEncoder()

train_df['wilayah_enc'] = le_wilayah.fit_transform(train_df['wilayah'])
train_df['komoditas_enc'] = le_komoditas.fit_transform(train_df['komoditas'])

test_df['wilayah_enc'] = le_wilayah.transform(test_df['wilayah'])
test_df['komoditas_enc'] = le_komoditas.transform(test_df['komoditas'])

# Pisahkan X dan y
FITUR = [
    'tahun', 'bulan', 'kuartal', 'wilayah_enc', 'komoditas_enc',
    'harga_lag1', 'harga_lag2', 'harga_lag3', 'harga_rolling3',
    'harga_lag12', 'sin_bulan', 'cos_bulan', 'is_lebaran_month',
    'tren_index', 'harga_rolling12'
]
TARGET = 'harga'

X_train = train_df[FITUR]
y_train = train_df[TARGET]
X_test = test_df[FITUR]
y_test = test_df[TARGET]

### g. Scalling

In [8]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=FITUR)
X_test_scaled  = pd.DataFrame(scaler.transform(X_test), columns=FITUR)

print("Scaling dengan RobustScaler selesai, siap disave!")

Scaling dengan RobustScaler selesai, siap disave!

### h. Save the Preprocessing Result

In [9]:
import joblib
import os 

BASE_DIR = os.path.abspath('')

PROCESSED_DIR = os.path.join(BASE_DIR, '..', 'data', 'processed')
API_MODELS    = os.path.join(BASE_DIR, '..', 'api', 'models')
MODELS_DIR    = os.path.join(BASE_DIR, '..', 'models')

os.makedirs(PROCESSED_DIR, exist_ok=True)
os.makedirs(API_MODELS,    exist_ok=True)
os.makedirs(MODELS_DIR,    exist_ok=True)

# Simpan data
X_train_scaled.to_csv(os.path.join(PROCESSED_DIR, 'X_train.csv'), index=False)
X_test_scaled.to_csv( os.path.join(PROCESSED_DIR, 'X_test.csv'),  index=False)
y_train.to_csv(       os.path.join(PROCESSED_DIR, 'y_train.csv'), index=False)
y_test.to_csv(        os.path.join(PROCESSED_DIR, 'y_test.csv'),  index=False)

# Simpan ke api/models/ (untuk serving)
joblib.dump(scaler,       os.path.join(API_MODELS, 'scaler.joblib'))
joblib.dump(le_wilayah,   os.path.join(API_MODELS, 'le_wilayah.joblib'))
joblib.dump(le_komoditas, os.path.join(API_MODELS, 'le_komoditas.joblib'))

# Simpan ke models/ (arsip lokal)
joblib.dump(scaler,       os.path.join(MODELS_DIR, 'scaler.joblib'))
joblib.dump(le_wilayah,   os.path.join(MODELS_DIR, 'le_wilayah.joblib'))
joblib.dump(le_komoditas, os.path.join(MODELS_DIR, 'le_komoditas.joblib'))

print("Semua artefak berhasil disimpan:")
print(f"  Data  → {os.path.abspath(PROCESSED_DIR)}")
print(f"  API   → {os.path.abspath(API_MODELS)}")
print(f"  Arsip → {os.path.abspath(MODELS_DIR)}")

Semua artefak berhasil disimpan:
  Data  → c:\Coding SDT\VS Code\Python\Semester 4\PBL\data\processed
  API   → c:\Coding SDT\VS Code\Python\Semester 4\PBL\api\models
  Arsip → c:\Coding SDT\VS Code\Python\Semester 4\PBL\models

### i. Split & Save Per-Komoditas Dataset

In [10]:
import os

PER_KOMODITAS_DIR = os.path.join(PROCESSED_DIR, 'per_komoditas')
os.makedirs(PER_KOMODITAS_DIR, exist_ok=True)

# Fitur untuk per-komoditas (drop komoditas_enc)
FITUR_KOMODITAS = [f for f in FITUR if f != 'komoditas_enc']

komoditas_list = test_df['komoditas'].unique()

for k in komoditas_list:
    folder_name = k.replace(' ', '_').replace('/', '-')
    k_dir = os.path.join(PER_KOMODITAS_DIR, folder_name)
    os.makedirs(k_dir, exist_ok=True)
    
    # Filter dataset
    train_k = train_df[train_df['komoditas'] == k]
    test_k  = test_df[test_df['komoditas'] == k]
    
    # Ambil fitur dan target
    X_train_k = train_k[FITUR_KOMODITAS]
    y_train_k = train_k[TARGET]
    X_test_k  = test_k[FITUR_KOMODITAS]
    y_test_k  = test_k[TARGET]
    
    # Save CSV
    X_train_k.to_csv(os.path.join(k_dir, 'X_train.csv'), index=False)
    y_train_k.to_csv(os.path.join(k_dir, 'y_train.csv'), index=False)
    X_test_k.to_csv(os.path.join(k_dir, 'X_test.csv'), index=False)
    y_test_k.to_csv(os.path.join(k_dir, 'y_test.csv'), index=False)

print(f"Berhasil memecah dan menyimpan dataset untuk {len(komoditas_list)} komoditas.")

Berhasil memecah dan menyimpan dataset untuk 21 komoditas.